apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splash.fullname" . }}-logstash-config
  labels:
    {{- include "splash.labels" . | nindent 4 }}
data:
  logstash.yml: |
{{ .Files.Get "files/logstash.yml" | indent 4 }}
  logstash.conf: |
{{ .Files.Get "files/logstash.conf" | indent 4 }}
  classify_batch.rb: |
{{ .Files.Get "files/classify_batch.rb" | indent 4 }}
  classify_rules.json: |
{{ .Files.Get "files/classify_rules.json" | indent 4 }}
