apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splash.fullname" . }}-logstash-config
  labels:
    {{- include "splash.labels" . | nindent 4 }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
    pipeline.workers: {{ .Values.pipeline.workers | int }}
    pipeline.batch.size: 500
    dead_letter_queue.enable: true
    dead_letter_queue.max_bytes: 1073741824
  logstash.conf: |
{{ .Files.Get "files/logstash.conf" | indent 4 }}
  classify_batch.rb: |
{{ .Files.Get "files/classify_batch.rb" | indent 4 }}
  classify_rules.json: |
{{ .Files.Get "files/classify_rules.json" | indent 4 }}
